service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: sa-east-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: production
    runtime: provided.al2
    lambdaHashingVersion: 20201221
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: 'https://apollofm.net/'
      SESSION_DRIVER: 'cookie'
      SESSION_LIFETIME: 120
      SESSION_DOMAIN: 'apollofm.net'
      TWITTER_CALLBACK_URL: 'https://apollofm.net/callbacks/twitter'
      LASTFM_API_URL: 'http://ws.audioscrobbler.com/2.0/'
      TWITTER_API_KEY: ${ssm:/TWITTER_API_KEY~true}
      TWITTER_API_SECRET: ${ssm:/TWITTER_API_SECRET~true}
      LASTFM_API_KEY: ${ssm:/LASTFM_API_KEY~true}
      APP_KEY: ${ssm:/APP_KEY~true}
package:
    # Directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - .env

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            - httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-80} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
